name: Simple Workflow

on: 
  push: 
    branches: [master, feature]
  pull_requests:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello Alien!
    
    - name: Run a multi-line script
      run: |
           echo More actions can be build here
           echo Bye!
